### ISSUE TITLE
Exclusion of sample file of asset

### ISSUE THREAD

**Issue by caliconiko** [ddorn/AsciidotsDebugger#11]
What is the dots file for
![image](https://user-images.githubusercontent.com/69907559/137625015-65fab3f0-cb52-4c33-aef1-dd4f10a2f18c.png)
?
Maybe include said file (and also other files used to for the assete) in the samples directory? :)

**Comment by ddorn** [comment]
Sadly, I do not have access to those files anymore, so I'm closing this issue :S
