### ISSUE TITLE
[enhancement] allow user to see class of characters

### ISSUE THREAD

**Issue by aaronjanse** [ddorn/AsciidotsDebugger#4]
It would be great if the user could do something (like holding shift) that would show the class of the char under the cursor.

This would help with AsciiDots development, and could help people understand warps if it displays where a warp links to.

Just an idea.

Btw, this is an amazing debugger. Thanks for building this.

**Comment by ddorn** [comment]
I was thinking of something like highlighting the companions wraps when hovering (or maybe with shift), but the class chars will be very usefull too !

I see two options for showing the class, either on a corner (say bottom right) or next to the cursor in the same way as the dots info, which one do you think is the best ?

Thanks ;) The only inspiration is your amazing language !

**Comment by aaronjanse** [comment]
> I was thinking of something like highlighting the companions wraps when hovering (or maybe with shift)

That would be amazing

> I see two options for showing the class, either on a corner (say bottom right) or next to the cursor in the same way as the dots info, which one do you think is the best ?

I think that it would be easier to focus on the char if its info is closer to the cursor, instead of moving the eyes a lot.

Thanks for the debugger, it rocks

**Comment by ddorn** [comment]
Thanks ! This was added through https://github.com/ddorn/AsciidotsDebugger/commit/ba85b2a0d142be7cdd41a3c00484ca616e0c6302 and https://github.com/ddorn/AsciidotsDebugger/commit/2cc9a57da5e614c02dc764880d9da3911aae8c03

I'll close this issue, but don't hesitate with other features suggestions ! ;)
