### ISSUE TITLE
[enhancement] add github pages link to repo description

### ISSUE THREAD

**Issue by aaronjanse** [ddorn/AsciidotsDebugger#5]
It isn't essential, but it would be a 5-second change that would help people find [this repo's beautiful website](https://ddorn.github.io/AsciidotsDebugger/)

<img width="1115" alt="screen shot 2017-09-26 at 6 19 41 pm" src="https://user-images.githubusercontent.com/16829510/30891310-6913b5c8-a2e7-11e7-8943-7cdd90617c9f.png">

Btw, this repo's source code is beautiful

**Comment by ddorn** [comment]
Thanks ! I didn't know this option :)
